# Generated by Django 4.0.6 on 2022-07-22 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cashtagauthormap',
            unique_together={('start', 'author')},
        ),
        migrations.AlterUniqueTogether(
            name='cashtagtweetmap',
            unique_together={('start', 'tweet')},
        ),
        migrations.AlterUniqueTogether(
            name='hashtagauthormap',
            unique_together={('start', 'author')},
        ),
        migrations.AlterUniqueTogether(
            name='hashtagtweetmap',
            unique_together={('start', 'tweet')},
        ),
        migrations.AlterUniqueTogether(
            name='mentiontweet',
            unique_together={('start', 'tweet')},
        ),
        migrations.AlterUniqueTogether(
            name='urls',
            unique_together={('start', 'tweet')},
        ),
    ]
